"""Add OAuth fields to user model

Revision ID: 3f4fc6c85151
Revises: 8505dda72996
Create Date: 2025-08-06 00:54:24.801488

"""
from alembic import op
import sqlalchemy as sa


revision = '3f4fc6c85151'
down_revision = '8505dda72996'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 