"""Initial migration

Revision ID: 94ed6ecaeb32
Revises: 
Create Date: 2025-08-05 17:30:54.321005

"""
from alembic import op
import sqlalchemy as sa


revision = '94ed6ecaeb32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 